# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import srpc_pb2 as srpc__pb2


class ShaniuServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BucketGet = channel.unary_unary(
                '/srpc.ShaniuService/BucketGet',
                request_serializer=srpc__pb2.BucketKeyRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                )
        self.BucketSet = channel.unary_unary(
                '/srpc.ShaniuService/BucketSet',
                request_serializer=srpc__pb2.BucketSetRequest.SerializeToString,
                response_deserializer=srpc__pb2.BucketSetResponse.FromString,
                )
        self.BucketDelete = channel.unary_unary(
                '/srpc.ShaniuService/BucketDelete',
                request_serializer=srpc__pb2.BucketRequest.SerializeToString,
                response_deserializer=srpc__pb2.Empty.FromString,
                )
        self.BucketKeys = channel.unary_unary(
                '/srpc.ShaniuService/BucketKeys',
                request_serializer=srpc__pb2.BucketRequest.SerializeToString,
                response_deserializer=srpc__pb2.BucketKeysResponse.FromString,
                )
        self.BucketLen = channel.unary_unary(
                '/srpc.ShaniuService/BucketLen',
                request_serializer=srpc__pb2.BucketRequest.SerializeToString,
                response_deserializer=srpc__pb2.LenResponse.FromString,
                )
        self.BucketGetAll = channel.unary_unary(
                '/srpc.ShaniuService/BucketGetAll',
                request_serializer=srpc__pb2.BucketRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                )
        self.BucketBuckets = channel.unary_unary(
                '/srpc.ShaniuService/BucketBuckets',
                request_serializer=srpc__pb2.Empty.SerializeToString,
                response_deserializer=srpc__pb2.BucketsResponse.FromString,
                )
        self.BucketWatch = channel.stream_stream(
                '/srpc.ShaniuService/BucketWatch',
                request_serializer=srpc__pb2.BucketWatchRequest.SerializeToString,
                response_deserializer=srpc__pb2.BucketWatchResponse.FromString,
                )
        self.SenderGetUserId = channel.unary_unary(
                '/srpc.ShaniuService/SenderGetUserId',
                request_serializer=srpc__pb2.SenderRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                )
        self.SenderGetUserName = channel.unary_unary(
                '/srpc.ShaniuService/SenderGetUserName',
                request_serializer=srpc__pb2.SenderRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                )
        self.SenderGetChatId = channel.unary_unary(
                '/srpc.ShaniuService/SenderGetChatId',
                request_serializer=srpc__pb2.SenderRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                )
        self.SenderGetChatName = channel.unary_unary(
                '/srpc.ShaniuService/SenderGetChatName',
                request_serializer=srpc__pb2.SenderRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                )
        self.SenderGetMessageId = channel.unary_unary(
                '/srpc.ShaniuService/SenderGetMessageId',
                request_serializer=srpc__pb2.SenderRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                )
        self.SenderIsAdmin = channel.unary_unary(
                '/srpc.ShaniuService/SenderIsAdmin',
                request_serializer=srpc__pb2.SenderRequest.SerializeToString,
                response_deserializer=srpc__pb2.BoolResponse.FromString,
                )
        self.SenderGetPlatform = channel.unary_unary(
                '/srpc.ShaniuService/SenderGetPlatform',
                request_serializer=srpc__pb2.SenderRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                )
        self.SenderGetBotId = channel.unary_unary(
                '/srpc.ShaniuService/SenderGetBotId',
                request_serializer=srpc__pb2.SenderRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                )
        self.SenderGetContent = channel.unary_unary(
                '/srpc.ShaniuService/SenderGetContent',
                request_serializer=srpc__pb2.SenderRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                )
        self.SenderSetContent = channel.unary_unary(
                '/srpc.ShaniuService/SenderSetContent',
                request_serializer=srpc__pb2.SenderContentRequest.SerializeToString,
                response_deserializer=srpc__pb2.Empty.FromString,
                )
        self.SenderContinue = channel.unary_unary(
                '/srpc.ShaniuService/SenderContinue',
                request_serializer=srpc__pb2.SenderRequest.SerializeToString,
                response_deserializer=srpc__pb2.Empty.FromString,
                )
        self.SenderListen = channel.stream_stream(
                '/srpc.ShaniuService/SenderListen',
                request_serializer=srpc__pb2.SenderListenRequest.SerializeToString,
                response_deserializer=srpc__pb2.SenderListenResponse.FromString,
                )
        self.SenderEvent = channel.unary_unary(
                '/srpc.ShaniuService/SenderEvent',
                request_serializer=srpc__pb2.SenderRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                )
        self.SenderReply = channel.unary_unary(
                '/srpc.ShaniuService/SenderReply',
                request_serializer=srpc__pb2.ReplyRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                )
        self.SenderParam = channel.unary_unary(
                '/srpc.ShaniuService/SenderParam',
                request_serializer=srpc__pb2.ReplyRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                )
        self.SenderAction = channel.unary_unary(
                '/srpc.ShaniuService/SenderAction',
                request_serializer=srpc__pb2.ReplyRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                )
        self.SenderDestroy = channel.unary_unary(
                '/srpc.ShaniuService/SenderDestroy',
                request_serializer=srpc__pb2.ReplyRequest.SerializeToString,
                response_deserializer=srpc__pb2.Empty.FromString,
                )
        self.AdapterRegist = channel.stream_stream(
                '/srpc.ShaniuService/AdapterRegist',
                request_serializer=srpc__pb2.AdapterRegistRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                )
        self.AdapterReceive = channel.unary_unary(
                '/srpc.ShaniuService/AdapterReceive',
                request_serializer=srpc__pb2.AdapterRequest.SerializeToString,
                response_deserializer=srpc__pb2.Empty.FromString,
                )
        self.AdapterPush = channel.unary_unary(
                '/srpc.ShaniuService/AdapterPush',
                request_serializer=srpc__pb2.AdapterRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                )
        self.AdapterDestroy = channel.unary_unary(
                '/srpc.ShaniuService/AdapterDestroy',
                request_serializer=srpc__pb2.AdapterRequest.SerializeToString,
                response_deserializer=srpc__pb2.Empty.FromString,
                )
        self.AdapterSender = channel.unary_unary(
                '/srpc.ShaniuService/AdapterSender',
                request_serializer=srpc__pb2.AdapterRequest.SerializeToString,
                response_deserializer=srpc__pb2.Default.FromString,
                )
        self.Console = channel.unary_unary(
                '/srpc.ShaniuService/Console',
                request_serializer=srpc__pb2.ConsoleRequest.SerializeToString,
                response_deserializer=srpc__pb2.Empty.FromString,
                )


class ShaniuServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BucketGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BucketSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BucketDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BucketKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BucketLen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BucketGetAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BucketBuckets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BucketWatch(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderGetUserId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderGetUserName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderGetChatId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderGetChatName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderGetMessageId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderIsAdmin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderGetPlatform(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderGetBotId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderGetContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderSetContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderContinue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderListen(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderReply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderParam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SenderDestroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdapterRegist(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdapterReceive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdapterPush(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdapterDestroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdapterSender(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Console(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShaniuServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BucketGet': grpc.unary_unary_rpc_method_handler(
                    servicer.BucketGet,
                    request_deserializer=srpc__pb2.BucketKeyRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'BucketSet': grpc.unary_unary_rpc_method_handler(
                    servicer.BucketSet,
                    request_deserializer=srpc__pb2.BucketSetRequest.FromString,
                    response_serializer=srpc__pb2.BucketSetResponse.SerializeToString,
            ),
            'BucketDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.BucketDelete,
                    request_deserializer=srpc__pb2.BucketRequest.FromString,
                    response_serializer=srpc__pb2.Empty.SerializeToString,
            ),
            'BucketKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.BucketKeys,
                    request_deserializer=srpc__pb2.BucketRequest.FromString,
                    response_serializer=srpc__pb2.BucketKeysResponse.SerializeToString,
            ),
            'BucketLen': grpc.unary_unary_rpc_method_handler(
                    servicer.BucketLen,
                    request_deserializer=srpc__pb2.BucketRequest.FromString,
                    response_serializer=srpc__pb2.LenResponse.SerializeToString,
            ),
            'BucketGetAll': grpc.unary_unary_rpc_method_handler(
                    servicer.BucketGetAll,
                    request_deserializer=srpc__pb2.BucketRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'BucketBuckets': grpc.unary_unary_rpc_method_handler(
                    servicer.BucketBuckets,
                    request_deserializer=srpc__pb2.Empty.FromString,
                    response_serializer=srpc__pb2.BucketsResponse.SerializeToString,
            ),
            'BucketWatch': grpc.stream_stream_rpc_method_handler(
                    servicer.BucketWatch,
                    request_deserializer=srpc__pb2.BucketWatchRequest.FromString,
                    response_serializer=srpc__pb2.BucketWatchResponse.SerializeToString,
            ),
            'SenderGetUserId': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderGetUserId,
                    request_deserializer=srpc__pb2.SenderRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'SenderGetUserName': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderGetUserName,
                    request_deserializer=srpc__pb2.SenderRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'SenderGetChatId': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderGetChatId,
                    request_deserializer=srpc__pb2.SenderRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'SenderGetChatName': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderGetChatName,
                    request_deserializer=srpc__pb2.SenderRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'SenderGetMessageId': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderGetMessageId,
                    request_deserializer=srpc__pb2.SenderRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'SenderIsAdmin': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderIsAdmin,
                    request_deserializer=srpc__pb2.SenderRequest.FromString,
                    response_serializer=srpc__pb2.BoolResponse.SerializeToString,
            ),
            'SenderGetPlatform': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderGetPlatform,
                    request_deserializer=srpc__pb2.SenderRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'SenderGetBotId': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderGetBotId,
                    request_deserializer=srpc__pb2.SenderRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'SenderGetContent': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderGetContent,
                    request_deserializer=srpc__pb2.SenderRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'SenderSetContent': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderSetContent,
                    request_deserializer=srpc__pb2.SenderContentRequest.FromString,
                    response_serializer=srpc__pb2.Empty.SerializeToString,
            ),
            'SenderContinue': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderContinue,
                    request_deserializer=srpc__pb2.SenderRequest.FromString,
                    response_serializer=srpc__pb2.Empty.SerializeToString,
            ),
            'SenderListen': grpc.stream_stream_rpc_method_handler(
                    servicer.SenderListen,
                    request_deserializer=srpc__pb2.SenderListenRequest.FromString,
                    response_serializer=srpc__pb2.SenderListenResponse.SerializeToString,
            ),
            'SenderEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderEvent,
                    request_deserializer=srpc__pb2.SenderRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'SenderReply': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderReply,
                    request_deserializer=srpc__pb2.ReplyRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'SenderParam': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderParam,
                    request_deserializer=srpc__pb2.ReplyRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'SenderAction': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderAction,
                    request_deserializer=srpc__pb2.ReplyRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'SenderDestroy': grpc.unary_unary_rpc_method_handler(
                    servicer.SenderDestroy,
                    request_deserializer=srpc__pb2.ReplyRequest.FromString,
                    response_serializer=srpc__pb2.Empty.SerializeToString,
            ),
            'AdapterRegist': grpc.stream_stream_rpc_method_handler(
                    servicer.AdapterRegist,
                    request_deserializer=srpc__pb2.AdapterRegistRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'AdapterReceive': grpc.unary_unary_rpc_method_handler(
                    servicer.AdapterReceive,
                    request_deserializer=srpc__pb2.AdapterRequest.FromString,
                    response_serializer=srpc__pb2.Empty.SerializeToString,
            ),
            'AdapterPush': grpc.unary_unary_rpc_method_handler(
                    servicer.AdapterPush,
                    request_deserializer=srpc__pb2.AdapterRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'AdapterDestroy': grpc.unary_unary_rpc_method_handler(
                    servicer.AdapterDestroy,
                    request_deserializer=srpc__pb2.AdapterRequest.FromString,
                    response_serializer=srpc__pb2.Empty.SerializeToString,
            ),
            'AdapterSender': grpc.unary_unary_rpc_method_handler(
                    servicer.AdapterSender,
                    request_deserializer=srpc__pb2.AdapterRequest.FromString,
                    response_serializer=srpc__pb2.Default.SerializeToString,
            ),
            'Console': grpc.unary_unary_rpc_method_handler(
                    servicer.Console,
                    request_deserializer=srpc__pb2.ConsoleRequest.FromString,
                    response_serializer=srpc__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'srpc.ShaniuService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ShaniuService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BucketGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srpc.ShaniuService/BucketGet',
            srpc__pb2.BucketKeyRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BucketSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srpc.ShaniuService/BucketSet',
            srpc__pb2.BucketSetRequest.SerializeToString,
            srpc__pb2.BucketSetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BucketDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srpc.ShaniuService/BucketDelete',
            srpc__pb2.BucketRequest.SerializeToString,
            srpc__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BucketKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srpc.ShaniuService/BucketKeys',
            srpc__pb2.BucketRequest.SerializeToString,
            srpc__pb2.BucketKeysResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BucketLen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srpc.ShaniuService/BucketLen',
            srpc__pb2.BucketRequest.SerializeToString,
            srpc__pb2.LenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BucketGetAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srpc.ShaniuService/BucketGetAll',
            srpc__pb2.BucketRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BucketBuckets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srpc.ShaniuService/BucketBuckets',
            srpc__pb2.Empty.SerializeToString,
            srpc__pb2.BucketsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BucketWatch(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/srpc.ShaniuService/BucketWatch',
            srpc__pb2.BucketWatchRequest.SerializeToString,
            srpc__pb2.BucketWatchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SenderGetUserId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srpc.ShaniuService/SenderGetUserId',
            srpc__pb2.SenderRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SenderGetUserName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srpc.ShaniuService/SenderGetUserName',
            srpc__pb2.SenderRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SenderGetChatId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srpc.ShaniuService/SenderGetChatId',
            srpc__pb2.SenderRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SenderGetChatName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srpc.ShaniuService/SenderGetChatName',
            srpc__pb2.SenderRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SenderGetMessageId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srpc.ShaniuService/SenderGetMessageId',
            srpc__pb2.SenderRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SenderIsAdmin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srpc.ShaniuService/SenderIsAdmin',
            srpc__pb2.SenderRequest.SerializeToString,
            srpc__pb2.BoolResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SenderGetPlatform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srpc.ShaniuService/SenderGetPlatform',
            srpc__pb2.SenderRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SenderGetBotId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srpc.ShaniuService/SenderGetBotId',
            srpc__pb2.SenderRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SenderGetContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srpc.ShaniuService/SenderGetContent',
            srpc__pb2.SenderRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SenderSetContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srpc.ShaniuService/SenderSetContent',
            srpc__pb2.SenderContentRequest.SerializeToString,
            srpc__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SenderContinue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srpc.ShaniuService/SenderContinue',
            srpc__pb2.SenderRequest.SerializeToString,
            srpc__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SenderListen(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/srpc.ShaniuService/SenderListen',
            srpc__pb2.SenderListenRequest.SerializeToString,
            srpc__pb2.SenderListenResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SenderEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srpc.ShaniuService/SenderEvent',
            srpc__pb2.SenderRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SenderReply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srpc.ShaniuService/SenderReply',
            srpc__pb2.ReplyRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SenderParam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srpc.ShaniuService/SenderParam',
            srpc__pb2.ReplyRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SenderAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srpc.ShaniuService/SenderAction',
            srpc__pb2.ReplyRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SenderDestroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srpc.ShaniuService/SenderDestroy',
            srpc__pb2.ReplyRequest.SerializeToString,
            srpc__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AdapterRegist(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/srpc.ShaniuService/AdapterRegist',
            srpc__pb2.AdapterRegistRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AdapterReceive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srpc.ShaniuService/AdapterReceive',
            srpc__pb2.AdapterRequest.SerializeToString,
            srpc__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AdapterPush(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srpc.ShaniuService/AdapterPush',
            srpc__pb2.AdapterRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AdapterDestroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srpc.ShaniuService/AdapterDestroy',
            srpc__pb2.AdapterRequest.SerializeToString,
            srpc__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AdapterSender(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srpc.ShaniuService/AdapterSender',
            srpc__pb2.AdapterRequest.SerializeToString,
            srpc__pb2.Default.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Console(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/srpc.ShaniuService/Console',
            srpc__pb2.ConsoleRequest.SerializeToString,
            srpc__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
