// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: srpc.proto

package srpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ShaniuService_BucketGet_FullMethodName          = "/srpc.ShaniuService/BucketGet"
	ShaniuService_BucketSet_FullMethodName          = "/srpc.ShaniuService/BucketSet"
	ShaniuService_BucketDelete_FullMethodName       = "/srpc.ShaniuService/BucketDelete"
	ShaniuService_BucketKeys_FullMethodName         = "/srpc.ShaniuService/BucketKeys"
	ShaniuService_BucketLen_FullMethodName          = "/srpc.ShaniuService/BucketLen"
	ShaniuService_BucketGetAll_FullMethodName       = "/srpc.ShaniuService/BucketGetAll"
	ShaniuService_BucketBuckets_FullMethodName      = "/srpc.ShaniuService/BucketBuckets"
	ShaniuService_BucketWatch_FullMethodName        = "/srpc.ShaniuService/BucketWatch"
	ShaniuService_SenderGetUserId_FullMethodName    = "/srpc.ShaniuService/SenderGetUserId"
	ShaniuService_SenderGetUserName_FullMethodName  = "/srpc.ShaniuService/SenderGetUserName"
	ShaniuService_SenderGetChatId_FullMethodName    = "/srpc.ShaniuService/SenderGetChatId"
	ShaniuService_SenderGetChatName_FullMethodName  = "/srpc.ShaniuService/SenderGetChatName"
	ShaniuService_SenderGetMessageId_FullMethodName = "/srpc.ShaniuService/SenderGetMessageId"
	ShaniuService_SenderIsAdmin_FullMethodName      = "/srpc.ShaniuService/SenderIsAdmin"
	ShaniuService_SenderGetPlatform_FullMethodName  = "/srpc.ShaniuService/SenderGetPlatform"
	ShaniuService_SenderGetBotId_FullMethodName     = "/srpc.ShaniuService/SenderGetBotId"
	ShaniuService_SenderGetContent_FullMethodName   = "/srpc.ShaniuService/SenderGetContent"
	ShaniuService_SenderSetContent_FullMethodName   = "/srpc.ShaniuService/SenderSetContent"
	ShaniuService_SenderContinue_FullMethodName     = "/srpc.ShaniuService/SenderContinue"
	ShaniuService_SenderListen_FullMethodName       = "/srpc.ShaniuService/SenderListen"
	ShaniuService_SenderEvent_FullMethodName        = "/srpc.ShaniuService/SenderEvent"
	ShaniuService_SenderReply_FullMethodName        = "/srpc.ShaniuService/SenderReply"
	ShaniuService_SenderParam_FullMethodName        = "/srpc.ShaniuService/SenderParam"
	ShaniuService_SenderAction_FullMethodName       = "/srpc.ShaniuService/SenderAction"
	ShaniuService_SenderDestroy_FullMethodName      = "/srpc.ShaniuService/SenderDestroy"
	ShaniuService_AdapterRegist_FullMethodName      = "/srpc.ShaniuService/AdapterRegist"
	ShaniuService_AdapterReceive_FullMethodName     = "/srpc.ShaniuService/AdapterReceive"
	ShaniuService_AdapterPush_FullMethodName        = "/srpc.ShaniuService/AdapterPush"
	ShaniuService_AdapterDestroy_FullMethodName     = "/srpc.ShaniuService/AdapterDestroy"
	ShaniuService_AdapterSender_FullMethodName      = "/srpc.ShaniuService/AdapterSender"
	ShaniuService_Console_FullMethodName            = "/srpc.ShaniuService/Console"
)

// ShaniuServiceClient is the client API for ShaniuService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShaniuServiceClient interface {
	BucketGet(ctx context.Context, in *BucketKeyRequest, opts ...grpc.CallOption) (*Default, error)
	BucketSet(ctx context.Context, in *BucketSetRequest, opts ...grpc.CallOption) (*BucketSetResponse, error)
	BucketDelete(ctx context.Context, in *BucketRequest, opts ...grpc.CallOption) (*Empty, error)
	BucketKeys(ctx context.Context, in *BucketRequest, opts ...grpc.CallOption) (*BucketKeysResponse, error)
	BucketLen(ctx context.Context, in *BucketRequest, opts ...grpc.CallOption) (*LenResponse, error)
	BucketGetAll(ctx context.Context, in *BucketRequest, opts ...grpc.CallOption) (*Default, error)
	BucketBuckets(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BucketsResponse, error)
	BucketWatch(ctx context.Context, opts ...grpc.CallOption) (ShaniuService_BucketWatchClient, error)
	SenderGetUserId(ctx context.Context, in *SenderRequest, opts ...grpc.CallOption) (*Default, error)
	SenderGetUserName(ctx context.Context, in *SenderRequest, opts ...grpc.CallOption) (*Default, error)
	SenderGetChatId(ctx context.Context, in *SenderRequest, opts ...grpc.CallOption) (*Default, error)
	SenderGetChatName(ctx context.Context, in *SenderRequest, opts ...grpc.CallOption) (*Default, error)
	SenderGetMessageId(ctx context.Context, in *SenderRequest, opts ...grpc.CallOption) (*Default, error)
	SenderIsAdmin(ctx context.Context, in *SenderRequest, opts ...grpc.CallOption) (*BoolResponse, error)
	SenderGetPlatform(ctx context.Context, in *SenderRequest, opts ...grpc.CallOption) (*Default, error)
	SenderGetBotId(ctx context.Context, in *SenderRequest, opts ...grpc.CallOption) (*Default, error)
	SenderGetContent(ctx context.Context, in *SenderRequest, opts ...grpc.CallOption) (*Default, error)
	SenderSetContent(ctx context.Context, in *SenderContentRequest, opts ...grpc.CallOption) (*Empty, error)
	SenderContinue(ctx context.Context, in *SenderRequest, opts ...grpc.CallOption) (*Empty, error)
	SenderListen(ctx context.Context, opts ...grpc.CallOption) (ShaniuService_SenderListenClient, error)
	SenderEvent(ctx context.Context, in *SenderRequest, opts ...grpc.CallOption) (*Default, error)
	SenderReply(ctx context.Context, in *ReplyRequest, opts ...grpc.CallOption) (*Default, error)
	SenderParam(ctx context.Context, in *ReplyRequest, opts ...grpc.CallOption) (*Default, error)
	SenderAction(ctx context.Context, in *ReplyRequest, opts ...grpc.CallOption) (*Default, error)
	SenderDestroy(ctx context.Context, in *ReplyRequest, opts ...grpc.CallOption) (*Empty, error)
	AdapterRegist(ctx context.Context, opts ...grpc.CallOption) (ShaniuService_AdapterRegistClient, error)
	AdapterReceive(ctx context.Context, in *AdapterRequest, opts ...grpc.CallOption) (*Empty, error)
	AdapterPush(ctx context.Context, in *AdapterRequest, opts ...grpc.CallOption) (*Default, error)
	AdapterDestroy(ctx context.Context, in *AdapterRequest, opts ...grpc.CallOption) (*Empty, error)
	AdapterSender(ctx context.Context, in *AdapterRequest, opts ...grpc.CallOption) (*Default, error)
	Console(ctx context.Context, in *ConsoleRequest, opts ...grpc.CallOption) (*Empty, error)
}

type shaniuServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShaniuServiceClient(cc grpc.ClientConnInterface) ShaniuServiceClient {
	return &shaniuServiceClient{cc}
}

func (c *shaniuServiceClient) BucketGet(ctx context.Context, in *BucketKeyRequest, opts ...grpc.CallOption) (*Default, error) {
	out := new(Default)
	err := c.cc.Invoke(ctx, ShaniuService_BucketGet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaniuServiceClient) BucketSet(ctx context.Context, in *BucketSetRequest, opts ...grpc.CallOption) (*BucketSetResponse, error) {
	out := new(BucketSetResponse)
	err := c.cc.Invoke(ctx, ShaniuService_BucketSet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaniuServiceClient) BucketDelete(ctx context.Context, in *BucketRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, ShaniuService_BucketDelete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaniuServiceClient) BucketKeys(ctx context.Context, in *BucketRequest, opts ...grpc.CallOption) (*BucketKeysResponse, error) {
	out := new(BucketKeysResponse)
	err := c.cc.Invoke(ctx, ShaniuService_BucketKeys_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaniuServiceClient) BucketLen(ctx context.Context, in *BucketRequest, opts ...grpc.CallOption) (*LenResponse, error) {
	out := new(LenResponse)
	err := c.cc.Invoke(ctx, ShaniuService_BucketLen_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaniuServiceClient) BucketGetAll(ctx context.Context, in *BucketRequest, opts ...grpc.CallOption) (*Default, error) {
	out := new(Default)
	err := c.cc.Invoke(ctx, ShaniuService_BucketGetAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaniuServiceClient) BucketBuckets(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BucketsResponse, error) {
	out := new(BucketsResponse)
	err := c.cc.Invoke(ctx, ShaniuService_BucketBuckets_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaniuServiceClient) BucketWatch(ctx context.Context, opts ...grpc.CallOption) (ShaniuService_BucketWatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &ShaniuService_ServiceDesc.Streams[0], ShaniuService_BucketWatch_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &shaniuServiceBucketWatchClient{stream}
	return x, nil
}

type ShaniuService_BucketWatchClient interface {
	Send(*BucketWatchRequest) error
	Recv() (*BucketWatchResponse, error)
	grpc.ClientStream
}

type shaniuServiceBucketWatchClient struct {
	grpc.ClientStream
}

func (x *shaniuServiceBucketWatchClient) Send(m *BucketWatchRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *shaniuServiceBucketWatchClient) Recv() (*BucketWatchResponse, error) {
	m := new(BucketWatchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *shaniuServiceClient) SenderGetUserId(ctx context.Context, in *SenderRequest, opts ...grpc.CallOption) (*Default, error) {
	out := new(Default)
	err := c.cc.Invoke(ctx, ShaniuService_SenderGetUserId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaniuServiceClient) SenderGetUserName(ctx context.Context, in *SenderRequest, opts ...grpc.CallOption) (*Default, error) {
	out := new(Default)
	err := c.cc.Invoke(ctx, ShaniuService_SenderGetUserName_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaniuServiceClient) SenderGetChatId(ctx context.Context, in *SenderRequest, opts ...grpc.CallOption) (*Default, error) {
	out := new(Default)
	err := c.cc.Invoke(ctx, ShaniuService_SenderGetChatId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaniuServiceClient) SenderGetChatName(ctx context.Context, in *SenderRequest, opts ...grpc.CallOption) (*Default, error) {
	out := new(Default)
	err := c.cc.Invoke(ctx, ShaniuService_SenderGetChatName_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaniuServiceClient) SenderGetMessageId(ctx context.Context, in *SenderRequest, opts ...grpc.CallOption) (*Default, error) {
	out := new(Default)
	err := c.cc.Invoke(ctx, ShaniuService_SenderGetMessageId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaniuServiceClient) SenderIsAdmin(ctx context.Context, in *SenderRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, ShaniuService_SenderIsAdmin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaniuServiceClient) SenderGetPlatform(ctx context.Context, in *SenderRequest, opts ...grpc.CallOption) (*Default, error) {
	out := new(Default)
	err := c.cc.Invoke(ctx, ShaniuService_SenderGetPlatform_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaniuServiceClient) SenderGetBotId(ctx context.Context, in *SenderRequest, opts ...grpc.CallOption) (*Default, error) {
	out := new(Default)
	err := c.cc.Invoke(ctx, ShaniuService_SenderGetBotId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaniuServiceClient) SenderGetContent(ctx context.Context, in *SenderRequest, opts ...grpc.CallOption) (*Default, error) {
	out := new(Default)
	err := c.cc.Invoke(ctx, ShaniuService_SenderGetContent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaniuServiceClient) SenderSetContent(ctx context.Context, in *SenderContentRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, ShaniuService_SenderSetContent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaniuServiceClient) SenderContinue(ctx context.Context, in *SenderRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, ShaniuService_SenderContinue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaniuServiceClient) SenderListen(ctx context.Context, opts ...grpc.CallOption) (ShaniuService_SenderListenClient, error) {
	stream, err := c.cc.NewStream(ctx, &ShaniuService_ServiceDesc.Streams[1], ShaniuService_SenderListen_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &shaniuServiceSenderListenClient{stream}
	return x, nil
}

type ShaniuService_SenderListenClient interface {
	Send(*SenderListenRequest) error
	Recv() (*SenderListenResponse, error)
	grpc.ClientStream
}

type shaniuServiceSenderListenClient struct {
	grpc.ClientStream
}

func (x *shaniuServiceSenderListenClient) Send(m *SenderListenRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *shaniuServiceSenderListenClient) Recv() (*SenderListenResponse, error) {
	m := new(SenderListenResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *shaniuServiceClient) SenderEvent(ctx context.Context, in *SenderRequest, opts ...grpc.CallOption) (*Default, error) {
	out := new(Default)
	err := c.cc.Invoke(ctx, ShaniuService_SenderEvent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaniuServiceClient) SenderReply(ctx context.Context, in *ReplyRequest, opts ...grpc.CallOption) (*Default, error) {
	out := new(Default)
	err := c.cc.Invoke(ctx, ShaniuService_SenderReply_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaniuServiceClient) SenderParam(ctx context.Context, in *ReplyRequest, opts ...grpc.CallOption) (*Default, error) {
	out := new(Default)
	err := c.cc.Invoke(ctx, ShaniuService_SenderParam_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaniuServiceClient) SenderAction(ctx context.Context, in *ReplyRequest, opts ...grpc.CallOption) (*Default, error) {
	out := new(Default)
	err := c.cc.Invoke(ctx, ShaniuService_SenderAction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaniuServiceClient) SenderDestroy(ctx context.Context, in *ReplyRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, ShaniuService_SenderDestroy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaniuServiceClient) AdapterRegist(ctx context.Context, opts ...grpc.CallOption) (ShaniuService_AdapterRegistClient, error) {
	stream, err := c.cc.NewStream(ctx, &ShaniuService_ServiceDesc.Streams[2], ShaniuService_AdapterRegist_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &shaniuServiceAdapterRegistClient{stream}
	return x, nil
}

type ShaniuService_AdapterRegistClient interface {
	Send(*AdapterRegistRequest) error
	Recv() (*Default, error)
	grpc.ClientStream
}

type shaniuServiceAdapterRegistClient struct {
	grpc.ClientStream
}

func (x *shaniuServiceAdapterRegistClient) Send(m *AdapterRegistRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *shaniuServiceAdapterRegistClient) Recv() (*Default, error) {
	m := new(Default)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *shaniuServiceClient) AdapterReceive(ctx context.Context, in *AdapterRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, ShaniuService_AdapterReceive_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaniuServiceClient) AdapterPush(ctx context.Context, in *AdapterRequest, opts ...grpc.CallOption) (*Default, error) {
	out := new(Default)
	err := c.cc.Invoke(ctx, ShaniuService_AdapterPush_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaniuServiceClient) AdapterDestroy(ctx context.Context, in *AdapterRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, ShaniuService_AdapterDestroy_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaniuServiceClient) AdapterSender(ctx context.Context, in *AdapterRequest, opts ...grpc.CallOption) (*Default, error) {
	out := new(Default)
	err := c.cc.Invoke(ctx, ShaniuService_AdapterSender_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shaniuServiceClient) Console(ctx context.Context, in *ConsoleRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, ShaniuService_Console_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShaniuServiceServer is the server API for ShaniuService service.
// All implementations must embed UnimplementedShaniuServiceServer
// for forward compatibility
type ShaniuServiceServer interface {
	BucketGet(context.Context, *BucketKeyRequest) (*Default, error)
	BucketSet(context.Context, *BucketSetRequest) (*BucketSetResponse, error)
	BucketDelete(context.Context, *BucketRequest) (*Empty, error)
	BucketKeys(context.Context, *BucketRequest) (*BucketKeysResponse, error)
	BucketLen(context.Context, *BucketRequest) (*LenResponse, error)
	BucketGetAll(context.Context, *BucketRequest) (*Default, error)
	BucketBuckets(context.Context, *Empty) (*BucketsResponse, error)
	BucketWatch(ShaniuService_BucketWatchServer) error
	SenderGetUserId(context.Context, *SenderRequest) (*Default, error)
	SenderGetUserName(context.Context, *SenderRequest) (*Default, error)
	SenderGetChatId(context.Context, *SenderRequest) (*Default, error)
	SenderGetChatName(context.Context, *SenderRequest) (*Default, error)
	SenderGetMessageId(context.Context, *SenderRequest) (*Default, error)
	SenderIsAdmin(context.Context, *SenderRequest) (*BoolResponse, error)
	SenderGetPlatform(context.Context, *SenderRequest) (*Default, error)
	SenderGetBotId(context.Context, *SenderRequest) (*Default, error)
	SenderGetContent(context.Context, *SenderRequest) (*Default, error)
	SenderSetContent(context.Context, *SenderContentRequest) (*Empty, error)
	SenderContinue(context.Context, *SenderRequest) (*Empty, error)
	SenderListen(ShaniuService_SenderListenServer) error
	SenderEvent(context.Context, *SenderRequest) (*Default, error)
	SenderReply(context.Context, *ReplyRequest) (*Default, error)
	SenderParam(context.Context, *ReplyRequest) (*Default, error)
	SenderAction(context.Context, *ReplyRequest) (*Default, error)
	SenderDestroy(context.Context, *ReplyRequest) (*Empty, error)
	AdapterRegist(ShaniuService_AdapterRegistServer) error
	AdapterReceive(context.Context, *AdapterRequest) (*Empty, error)
	AdapterPush(context.Context, *AdapterRequest) (*Default, error)
	AdapterDestroy(context.Context, *AdapterRequest) (*Empty, error)
	AdapterSender(context.Context, *AdapterRequest) (*Default, error)
	Console(context.Context, *ConsoleRequest) (*Empty, error)
	mustEmbedUnimplementedShaniuServiceServer()
}

// UnimplementedShaniuServiceServer must be embedded to have forward compatible implementations.
type UnimplementedShaniuServiceServer struct {
}

func (UnimplementedShaniuServiceServer) BucketGet(context.Context, *BucketKeyRequest) (*Default, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BucketGet not implemented")
}
func (UnimplementedShaniuServiceServer) BucketSet(context.Context, *BucketSetRequest) (*BucketSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BucketSet not implemented")
}
func (UnimplementedShaniuServiceServer) BucketDelete(context.Context, *BucketRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BucketDelete not implemented")
}
func (UnimplementedShaniuServiceServer) BucketKeys(context.Context, *BucketRequest) (*BucketKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BucketKeys not implemented")
}
func (UnimplementedShaniuServiceServer) BucketLen(context.Context, *BucketRequest) (*LenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BucketLen not implemented")
}
func (UnimplementedShaniuServiceServer) BucketGetAll(context.Context, *BucketRequest) (*Default, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BucketGetAll not implemented")
}
func (UnimplementedShaniuServiceServer) BucketBuckets(context.Context, *Empty) (*BucketsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BucketBuckets not implemented")
}
func (UnimplementedShaniuServiceServer) BucketWatch(ShaniuService_BucketWatchServer) error {
	return status.Errorf(codes.Unimplemented, "method BucketWatch not implemented")
}
func (UnimplementedShaniuServiceServer) SenderGetUserId(context.Context, *SenderRequest) (*Default, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SenderGetUserId not implemented")
}
func (UnimplementedShaniuServiceServer) SenderGetUserName(context.Context, *SenderRequest) (*Default, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SenderGetUserName not implemented")
}
func (UnimplementedShaniuServiceServer) SenderGetChatId(context.Context, *SenderRequest) (*Default, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SenderGetChatId not implemented")
}
func (UnimplementedShaniuServiceServer) SenderGetChatName(context.Context, *SenderRequest) (*Default, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SenderGetChatName not implemented")
}
func (UnimplementedShaniuServiceServer) SenderGetMessageId(context.Context, *SenderRequest) (*Default, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SenderGetMessageId not implemented")
}
func (UnimplementedShaniuServiceServer) SenderIsAdmin(context.Context, *SenderRequest) (*BoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SenderIsAdmin not implemented")
}
func (UnimplementedShaniuServiceServer) SenderGetPlatform(context.Context, *SenderRequest) (*Default, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SenderGetPlatform not implemented")
}
func (UnimplementedShaniuServiceServer) SenderGetBotId(context.Context, *SenderRequest) (*Default, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SenderGetBotId not implemented")
}
func (UnimplementedShaniuServiceServer) SenderGetContent(context.Context, *SenderRequest) (*Default, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SenderGetContent not implemented")
}
func (UnimplementedShaniuServiceServer) SenderSetContent(context.Context, *SenderContentRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SenderSetContent not implemented")
}
func (UnimplementedShaniuServiceServer) SenderContinue(context.Context, *SenderRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SenderContinue not implemented")
}
func (UnimplementedShaniuServiceServer) SenderListen(ShaniuService_SenderListenServer) error {
	return status.Errorf(codes.Unimplemented, "method SenderListen not implemented")
}
func (UnimplementedShaniuServiceServer) SenderEvent(context.Context, *SenderRequest) (*Default, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SenderEvent not implemented")
}
func (UnimplementedShaniuServiceServer) SenderReply(context.Context, *ReplyRequest) (*Default, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SenderReply not implemented")
}
func (UnimplementedShaniuServiceServer) SenderParam(context.Context, *ReplyRequest) (*Default, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SenderParam not implemented")
}
func (UnimplementedShaniuServiceServer) SenderAction(context.Context, *ReplyRequest) (*Default, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SenderAction not implemented")
}
func (UnimplementedShaniuServiceServer) SenderDestroy(context.Context, *ReplyRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SenderDestroy not implemented")
}
func (UnimplementedShaniuServiceServer) AdapterRegist(ShaniuService_AdapterRegistServer) error {
	return status.Errorf(codes.Unimplemented, "method AdapterRegist not implemented")
}
func (UnimplementedShaniuServiceServer) AdapterReceive(context.Context, *AdapterRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdapterReceive not implemented")
}
func (UnimplementedShaniuServiceServer) AdapterPush(context.Context, *AdapterRequest) (*Default, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdapterPush not implemented")
}
func (UnimplementedShaniuServiceServer) AdapterDestroy(context.Context, *AdapterRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdapterDestroy not implemented")
}
func (UnimplementedShaniuServiceServer) AdapterSender(context.Context, *AdapterRequest) (*Default, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdapterSender not implemented")
}
func (UnimplementedShaniuServiceServer) Console(context.Context, *ConsoleRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Console not implemented")
}
func (UnimplementedShaniuServiceServer) mustEmbedUnimplementedShaniuServiceServer() {}

// UnsafeShaniuServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShaniuServiceServer will
// result in compilation errors.
type UnsafeShaniuServiceServer interface {
	mustEmbedUnimplementedShaniuServiceServer()
}

func RegisterShaniuServiceServer(s grpc.ServiceRegistrar, srv ShaniuServiceServer) {
	s.RegisterService(&ShaniuService_ServiceDesc, srv)
}

func _ShaniuService_BucketGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BucketKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaniuServiceServer).BucketGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaniuService_BucketGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaniuServiceServer).BucketGet(ctx, req.(*BucketKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaniuService_BucketSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BucketSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaniuServiceServer).BucketSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaniuService_BucketSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaniuServiceServer).BucketSet(ctx, req.(*BucketSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaniuService_BucketDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaniuServiceServer).BucketDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaniuService_BucketDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaniuServiceServer).BucketDelete(ctx, req.(*BucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaniuService_BucketKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaniuServiceServer).BucketKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaniuService_BucketKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaniuServiceServer).BucketKeys(ctx, req.(*BucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaniuService_BucketLen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaniuServiceServer).BucketLen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaniuService_BucketLen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaniuServiceServer).BucketLen(ctx, req.(*BucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaniuService_BucketGetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaniuServiceServer).BucketGetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaniuService_BucketGetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaniuServiceServer).BucketGetAll(ctx, req.(*BucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaniuService_BucketBuckets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaniuServiceServer).BucketBuckets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaniuService_BucketBuckets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaniuServiceServer).BucketBuckets(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaniuService_BucketWatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ShaniuServiceServer).BucketWatch(&shaniuServiceBucketWatchServer{stream})
}

type ShaniuService_BucketWatchServer interface {
	Send(*BucketWatchResponse) error
	Recv() (*BucketWatchRequest, error)
	grpc.ServerStream
}

type shaniuServiceBucketWatchServer struct {
	grpc.ServerStream
}

func (x *shaniuServiceBucketWatchServer) Send(m *BucketWatchResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *shaniuServiceBucketWatchServer) Recv() (*BucketWatchRequest, error) {
	m := new(BucketWatchRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ShaniuService_SenderGetUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaniuServiceServer).SenderGetUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaniuService_SenderGetUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaniuServiceServer).SenderGetUserId(ctx, req.(*SenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaniuService_SenderGetUserName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaniuServiceServer).SenderGetUserName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaniuService_SenderGetUserName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaniuServiceServer).SenderGetUserName(ctx, req.(*SenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaniuService_SenderGetChatId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaniuServiceServer).SenderGetChatId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaniuService_SenderGetChatId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaniuServiceServer).SenderGetChatId(ctx, req.(*SenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaniuService_SenderGetChatName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaniuServiceServer).SenderGetChatName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaniuService_SenderGetChatName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaniuServiceServer).SenderGetChatName(ctx, req.(*SenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaniuService_SenderGetMessageId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaniuServiceServer).SenderGetMessageId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaniuService_SenderGetMessageId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaniuServiceServer).SenderGetMessageId(ctx, req.(*SenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaniuService_SenderIsAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaniuServiceServer).SenderIsAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaniuService_SenderIsAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaniuServiceServer).SenderIsAdmin(ctx, req.(*SenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaniuService_SenderGetPlatform_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaniuServiceServer).SenderGetPlatform(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaniuService_SenderGetPlatform_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaniuServiceServer).SenderGetPlatform(ctx, req.(*SenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaniuService_SenderGetBotId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaniuServiceServer).SenderGetBotId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaniuService_SenderGetBotId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaniuServiceServer).SenderGetBotId(ctx, req.(*SenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaniuService_SenderGetContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaniuServiceServer).SenderGetContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaniuService_SenderGetContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaniuServiceServer).SenderGetContent(ctx, req.(*SenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaniuService_SenderSetContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SenderContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaniuServiceServer).SenderSetContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaniuService_SenderSetContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaniuServiceServer).SenderSetContent(ctx, req.(*SenderContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaniuService_SenderContinue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaniuServiceServer).SenderContinue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaniuService_SenderContinue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaniuServiceServer).SenderContinue(ctx, req.(*SenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaniuService_SenderListen_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ShaniuServiceServer).SenderListen(&shaniuServiceSenderListenServer{stream})
}

type ShaniuService_SenderListenServer interface {
	Send(*SenderListenResponse) error
	Recv() (*SenderListenRequest, error)
	grpc.ServerStream
}

type shaniuServiceSenderListenServer struct {
	grpc.ServerStream
}

func (x *shaniuServiceSenderListenServer) Send(m *SenderListenResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *shaniuServiceSenderListenServer) Recv() (*SenderListenRequest, error) {
	m := new(SenderListenRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ShaniuService_SenderEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaniuServiceServer).SenderEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaniuService_SenderEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaniuServiceServer).SenderEvent(ctx, req.(*SenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaniuService_SenderReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaniuServiceServer).SenderReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaniuService_SenderReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaniuServiceServer).SenderReply(ctx, req.(*ReplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaniuService_SenderParam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaniuServiceServer).SenderParam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaniuService_SenderParam_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaniuServiceServer).SenderParam(ctx, req.(*ReplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaniuService_SenderAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaniuServiceServer).SenderAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaniuService_SenderAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaniuServiceServer).SenderAction(ctx, req.(*ReplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaniuService_SenderDestroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaniuServiceServer).SenderDestroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaniuService_SenderDestroy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaniuServiceServer).SenderDestroy(ctx, req.(*ReplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaniuService_AdapterRegist_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ShaniuServiceServer).AdapterRegist(&shaniuServiceAdapterRegistServer{stream})
}

type ShaniuService_AdapterRegistServer interface {
	Send(*Default) error
	Recv() (*AdapterRegistRequest, error)
	grpc.ServerStream
}

type shaniuServiceAdapterRegistServer struct {
	grpc.ServerStream
}

func (x *shaniuServiceAdapterRegistServer) Send(m *Default) error {
	return x.ServerStream.SendMsg(m)
}

func (x *shaniuServiceAdapterRegistServer) Recv() (*AdapterRegistRequest, error) {
	m := new(AdapterRegistRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ShaniuService_AdapterReceive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdapterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaniuServiceServer).AdapterReceive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaniuService_AdapterReceive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaniuServiceServer).AdapterReceive(ctx, req.(*AdapterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaniuService_AdapterPush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdapterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaniuServiceServer).AdapterPush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaniuService_AdapterPush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaniuServiceServer).AdapterPush(ctx, req.(*AdapterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaniuService_AdapterDestroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdapterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaniuServiceServer).AdapterDestroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaniuService_AdapterDestroy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaniuServiceServer).AdapterDestroy(ctx, req.(*AdapterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaniuService_AdapterSender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdapterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaniuServiceServer).AdapterSender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaniuService_AdapterSender_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaniuServiceServer).AdapterSender(ctx, req.(*AdapterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShaniuService_Console_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShaniuServiceServer).Console(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShaniuService_Console_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShaniuServiceServer).Console(ctx, req.(*ConsoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShaniuService_ServiceDesc is the grpc.ServiceDesc for ShaniuService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShaniuService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "srpc.ShaniuService",
	HandlerType: (*ShaniuServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BucketGet",
			Handler:    _ShaniuService_BucketGet_Handler,
		},
		{
			MethodName: "BucketSet",
			Handler:    _ShaniuService_BucketSet_Handler,
		},
		{
			MethodName: "BucketDelete",
			Handler:    _ShaniuService_BucketDelete_Handler,
		},
		{
			MethodName: "BucketKeys",
			Handler:    _ShaniuService_BucketKeys_Handler,
		},
		{
			MethodName: "BucketLen",
			Handler:    _ShaniuService_BucketLen_Handler,
		},
		{
			MethodName: "BucketGetAll",
			Handler:    _ShaniuService_BucketGetAll_Handler,
		},
		{
			MethodName: "BucketBuckets",
			Handler:    _ShaniuService_BucketBuckets_Handler,
		},
		{
			MethodName: "SenderGetUserId",
			Handler:    _ShaniuService_SenderGetUserId_Handler,
		},
		{
			MethodName: "SenderGetUserName",
			Handler:    _ShaniuService_SenderGetUserName_Handler,
		},
		{
			MethodName: "SenderGetChatId",
			Handler:    _ShaniuService_SenderGetChatId_Handler,
		},
		{
			MethodName: "SenderGetChatName",
			Handler:    _ShaniuService_SenderGetChatName_Handler,
		},
		{
			MethodName: "SenderGetMessageId",
			Handler:    _ShaniuService_SenderGetMessageId_Handler,
		},
		{
			MethodName: "SenderIsAdmin",
			Handler:    _ShaniuService_SenderIsAdmin_Handler,
		},
		{
			MethodName: "SenderGetPlatform",
			Handler:    _ShaniuService_SenderGetPlatform_Handler,
		},
		{
			MethodName: "SenderGetBotId",
			Handler:    _ShaniuService_SenderGetBotId_Handler,
		},
		{
			MethodName: "SenderGetContent",
			Handler:    _ShaniuService_SenderGetContent_Handler,
		},
		{
			MethodName: "SenderSetContent",
			Handler:    _ShaniuService_SenderSetContent_Handler,
		},
		{
			MethodName: "SenderContinue",
			Handler:    _ShaniuService_SenderContinue_Handler,
		},
		{
			MethodName: "SenderEvent",
			Handler:    _ShaniuService_SenderEvent_Handler,
		},
		{
			MethodName: "SenderReply",
			Handler:    _ShaniuService_SenderReply_Handler,
		},
		{
			MethodName: "SenderParam",
			Handler:    _ShaniuService_SenderParam_Handler,
		},
		{
			MethodName: "SenderAction",
			Handler:    _ShaniuService_SenderAction_Handler,
		},
		{
			MethodName: "SenderDestroy",
			Handler:    _ShaniuService_SenderDestroy_Handler,
		},
		{
			MethodName: "AdapterReceive",
			Handler:    _ShaniuService_AdapterReceive_Handler,
		},
		{
			MethodName: "AdapterPush",
			Handler:    _ShaniuService_AdapterPush_Handler,
		},
		{
			MethodName: "AdapterDestroy",
			Handler:    _ShaniuService_AdapterDestroy_Handler,
		},
		{
			MethodName: "AdapterSender",
			Handler:    _ShaniuService_AdapterSender_Handler,
		},
		{
			MethodName: "Console",
			Handler:    _ShaniuService_Console_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BucketWatch",
			Handler:       _ShaniuService_BucketWatch_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SenderListen",
			Handler:       _ShaniuService_SenderListen_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "AdapterRegist",
			Handler:       _ShaniuService_AdapterRegist_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "srpc.proto",
}
